import { Box, Typography } from "@mui/material";

const ProductsTableHeader = () => {
	return (
		<>
			<Box
				display={"flex"}
				flexGrow={1}
				alignItems={"center"}
				bgcolor={"#677697"}
				p={"10px"}
			>
				<Typography
					variant={"subtitle1"}
					fontWeight={700}
					color="white"
					display={"flex"}
					flexBasis={"30px"}
				>
					№
				</Typography>
				<Typography
					variant={"subtitle1"}
					fontWeight={700}
					color="white"
					display={"flex"}
					flexBasis={"300px"}
				>
					Изображение
				</Typography>
				<Typography
					variant={"subtitle1"}
					fontWeight={700}
					color="white"
					display={"flex"}
					flexGrow={1}
					flexBasis={"250px"}
				>
					Наименование
				</Typography>
				<Typography
					variant={"subtitle1"}
					fontWeight={700}
					color="white"
					display={"flex"}
					flexBasis={"170px"}
				>
					Цена
				</Typography>
				<Typography
					variant={"subtitle1"}
					fontWeight={700}
					color="white"
					display={"flex"}
					flexBasis={"120px"}
				>
					Новинка
				</Typography>
				<Typography
					variant={"subtitle1"}
					fontWeight={700}
					color="white"
					display={"flex"}
					flexBasis={"150px"}
				>
					Рекомендуем
				</Typography>
				<Typography
					variant={"subtitle1"}
					fontWeight={700}
					color="white"
					display={"flex"}
					flexBasis={"200px"}
				>
					Активно
				</Typography>
				<Typography
					variant={"subtitle1"}
					fontWeight={700}
					color="white"
					display={"flex"}
					flexBasis={"200px"}
				>
					Действия
				</Typography>
			</Box>
		</>
	);
};

export { ProductsTableHeader };
